version: '3.7'

services:

  web:
    container_name: web-app
    build:
      context: ./
      dockerfile: Dockerfile.web
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    container_name: web-api
    build: 
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true